### PR TITLE
Add "new viewport port" support [ fix for issue #1137 ]

### PR DESCRIPTION
**Pull request by kabab**

### CODE REVIEW

**Comment by asturur** [comment]
how does this lofic behaves with viewboxes that have a scaling factor?

**Comment by kabab** [comment]
Will it s not about the viewBox attribute, you can check issue#1137 to understand the problem.

**Comment by asturur** [comment]
i understand the problem of the x and y attribute of the inner svg tag.
i`m asking if you checked this logic in combination with viewboxes attribute that have a scaling factor.

Does it stack correctly?

example:
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" width="1600" height="800" viewbox="10 10 500 500">

<svg preserveAspectRatio="none" x="10" y="10" width="300" height="300" style="fill: none;" viewBox="0 0 300 300">
	<rect x="2" y="2" width="100" height="80" fill="blue"></rect>
	<rect x="-2" y="-2" width="100" height="80" fill="orange"></rect>
	<svg preserveAspectRatio="none" x="100" y="100" width="300" height="150" style="fill: none;" viewBox="0 0 200 300">
		<rect x="10" y="10" width="100" height="30" fill="red"></rect>
	</svg>
</svg>
<svg preserveAspectRatio="none" x="0" y="100" width="3000" height="1500" style="fill: none;" viewBox="0 0 160 180">
	<rect x="10" y="10" width="10" height="60" fill="green"></rect>
</svg>
</svg>
```

is this svg rendering good?

**Comment by kabab** [comment]
@asturur  for the time being this pull request solve just (x, y) attribute problem.

**Comment by asturur** [comment]
please check #2399 for a more complete solution.

**Comment by asturur** [comment]
merged 2399.
thanks for giving input.

**Pull request closed without merging**
