### PR TITLE
Fix sortedObjects

### LINKED ISSUE #508: activeGroup object sort is incorrect
The zIndex of activeGroup objects is wrong.

objects before activeGroup selection:

objects in activeGroup selection:

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/138335-activegroup-object-sort-is-incorrect?utm_campaign=plugin&utm_content=tracker%2F23217&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F23217&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by asturur**
Fix sorting of objects in activeGroup.
Wait for screen for comparing

closes #508

### CODE REVIEW

**Comment by kangax** [comment]
A test would be great here as well

**Comment by asturur** [comment]
@kangax test done.
I cannot see anymore the test summary at the end of the script. Is this normal?

image

**Comment by kangax** [comment]
Strange... but the tests seem to pass. Maybe it's new jshint again.

**Comment by sapics** [comment]
I know little about Travis CI, but, it looks not work...
When I test kangax/master with build in my local Windows8.1 by qunit.html (below code), it has an error at unit test of group.

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>QUnit</title>
  <link rel="stylesheet" href="http://code.jquery.com/qunit/qunit-1.18.0.css">
</head>
<body>
  <div id="qunit"></div>
  <div id="qunit-fixture"></div>
  <script src="dist/fabric.js"></script>
  <script src="http://code.jquery.com/qunit/qunit-1.18.0.js"></script>
  <script src="test/unit/group.js"></script>
</body>
</html>
```

ws000012

**Comment by sapics** [comment]
This is the full version of qunit.html. There are more errors, and, some of them look not expected.
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>QUnit Test</title>
  <link rel="stylesheet" href="http://code.jquery.com/qunit/qunit-1.18.0.css">
</head>
<body>
  <div id="qunit"></div>
  <div id="qunit-fixture"></div>
  <script src="dist/fabric.js"></script>
  <script src="http://code.jquery.com/qunit/qunit-1.18.0.js"></script>
  <script src="test/unit/canvas.js"></script>
  <script src="test/unit/circle.js"></script>
  <script src="test/unit/color.js"></script>
  <script src="test/unit/ellipse.js"></script>
  <script src="test/unit/gradient.js"></script>
  <script src="test/unit/group.js"></script>
  <script src="test/unit/image_filters.js"></script>
  <script src="test/unit/image.js"></script>
  <script src="test/unit/itext.js"></script>
  <script src="test/unit/line.js"></script>
  <script src="test/unit/object_interactivity.js"></script>
  <script src="test/unit/object.js"></script>
  <script src="test/unit/observable.js"></script>
  <script src="test/unit/parser.js"></script>
  <script src="test/unit/path_group.js"></script>
  <script src="test/unit/path.js"></script>
  <script src="test/unit/pattern.js"></script>
  <script src="test/unit/polygon.js"></script>
  <script src="test/unit/polyline.js"></script>
  <script src="test/unit/rect.js"></script>
  <script src="test/unit/shadow.js"></script>
  <script src="test/unit/text.js"></script>
  <script src="test/unit/util.js"></script>
</body>
</html>
```

**Comment by asturur** [comment]
Screens of active group rendering in correct order.

image

image

image

image

**Comment by asturur** [comment]
@sapics there is an error in master branch, about latest fix.
I m trying to figure out best solution. The correct topic for your screen is the merged after 1.5.0 release

**Comment by sapics** [comment]
@asturur Thank you for checking!

Sorry, below comment is not about this PR, but qunit test. (Should I create new issue?)

I am afraid that tests of qunit do not work in Travis CI.
I make a PR #2136 which is come from your correct fix #2099.
It is a bug of test/unit/shadow.js, but it should be noticed by Travis CI when you make a pull request #2099, isn't it?
For me, fabric.js is a first github, therefore, I know littel about Travis CI function.

**Comment by asturur** [comment]
@sapics can i have your email? or please drop me an email in the mail of my profile.

**Comment by sapics** [comment]
Sure! I e-mail to you!

**Comment by asturur** [comment]
@kangax  cleaned the PR from unrelated comments ( @sapics your qtest unit html was very usefull to me thanks, i forgot it ) and i think this pr is ready for your final check.

**Comment by kangax** [comment]
@asturur could you please update change log as well when you get a chance (I'm on the phone right now)

**Comment by asturur** [comment]
You can live the changelog always to me, if i don't tell you i disappear for some period.
I prefer you focus on decision to merge what when if.

**Pull request merged**
