### PR TITLE
Fix getPointer for canvas in scrolled elements

### PR DESCRIPTION
**Pull request by specialkk**
This restores some of the changes that #407 made to fix the issue that has since reappeared. I've also fixed the documentation for the signature on the Canvas getPointer method (the second one was undocumented, the third was unnecessary).

### CODE REVIEW

**Comment by asturur** [comment]
could you make an example of what case is failing with current code and which one is fixed now?

**Comment by rockmacaca** [comment]
Sure, I'll try to find some time to make one, it's rather simple. I think all that is needed is a canvas with a large top margin inside an element with `overflow: auto`.

**Comment by asturur** [comment]
any time for showing the failing cases?

**Comment by rockmacaca** [comment]
http://jsfiddle.net/n7qonqcg/2/

I don't have access to my usual setup to build fabric with the new changes, but here is a failing case. As it turns out, I can only reproduce it for overflowing children in a fixed position container.

In the fiddle, dragging the picture so the cursor is outside the bounds of any elements that are causing the container to overflow (the blue spacer div or the orange canvas container) will calculate an incorrect pointer position.

**Comment by specialkk** [comment]
It looks like this got fixed at some point with the changes for 2.0. It's still an issue for the latest build in 1.x, but I think it's safe to close this.

**Pull request closed without merging**
