### PR TITLE
fix unit test canvas.js

### PR DESCRIPTION
**Pull request by sapics**
fix test/unit/canvas.js just remove unnecessary character "c"

### CODE REVIEW

**Comment by asturur** [comment]
hawkeye!

**Comment by sapics** [comment]
@asturur Now I try to test your awesome fix about group initialization, just time!! :)

**Comment by kangax** [comment]
Hm, this should have been caught by jshint... But I guess we don't lint test files?

**Comment by sapics** [comment]
It looks no check to test/unit/*.js.
I guess that `node test.js` also dose not work.

**Comment by sapics** [comment]
@kangax Awesome! Thank you for your great hard work for test!!!

**Pull request merged**
