### PR TITLE
preserveObjectStacking Problem #3095

### PR DESCRIPTION
**Pull request by neopheus**
Solution for problem : 
make small object on top of active one selectable with preserve object stacking true #3095 
+ with backward compatibility

### CODE REVIEW

**Comment by saadqbal** [comment]
Issue:   You cannot resize the object from its controls when its below another object. Please see the jsfiddle for reference:
[https://jsfiddle.net/ecvctazk/35/](https://jsfiddle.net/ecvctazk/35/)

**Comment by neopheus** [comment]
Example with new code :

https://jsfiddle.net/ecvctazk/37/

**Comment by saadqbal** [comment]
Bring the Black box to the edge of the red box and then try to resize the red box from the right handles. It won't resize

**Comment by saadqbal** [comment]
Try resizing the red box with the handles that are over the black box. 
[https://jsfiddle.net/ecvctazk/39/](https://jsfiddle.net/ecvctazk/39/)

**Comment by neopheus** [comment]
Like this : https://jsfiddle.net/ecvctazk/48/

**Comment by neopheus** [comment]
With the new build : https://jsfiddle.net/ecvctazk/49/

**Comment by saadqbal** [comment]
Yup. thats exactly what I wanted

**Comment by asturur** [comment]
i do not feel like adding ANOTHER flag. 
I prefer to find a way to select an object, when there is some race condition, basing on area, distance from center, or whatever may help us. but no other flags.

**Comment by neopheus** [comment]
I agree with you

But in this case, as there has been a major change functioning. Adding a backward compatibility option seems an appropriate solution

**Comment by neopheus** [comment]
jsfiddle refresh : https://jsfiddle.net/ecvctazk/53/

**Comment by neopheus** [comment]
new pull request : https://github.com/kangax/fabric.js/pull/3178
can you close this pull ?
Thank

**Pull request closed without merging**
