### PR TITLE
added image crop ToSVG support

### LINKED ISSUE #4708: SVG output does not respect Image crop attributes
Below fiddle uses height, width, cropX and cropY attributed in the way V2 suggests. Cropping happens correctly on canvas but upon downloading the SVG, the entire image is shown.

## Version
2.0

## Test Case
http://jsfiddle.net/Da7SP/841/
## Expected Behavior
Image must be cropped in SVG similar to canvas
## Actual Behavior
Entire image is shown in SVG

### LINKED ISSUE #4736: Scale image source of Texture Pattern Brush
## Version
2.0.1

## Test Case
http://jsfiddle.net/kephin/23hLLrkj/21/

## Expected Behavior
I'm trying to use texture pattern brush to mimic the eraser function, so I need to scale the source image of the texturePatternBrush to fit with the original canvas

## Actual Behavior
Cannot scale the image when using texturePatternBrush.

### PR DESCRIPTION
**Pull request by asturur**
close #4708

Add a clipPath to image toSVG in order to make crop working

image

image

### CODE REVIEW

**Comment by asturur** [comment]
Needs some test anyway

**Comment by kephin** [comment]
Hi, I saw you referenced the #4736 to #4738. But I don't see the connections between cropping image and scaling it. Do you mind sort of explaining for a little bit, thanks a lot!

**Comment by asturur** [comment]
i miss referenced and corrected later. :(

**Comment by AvaelKross** [comment]
@asturur 
```
'" width="', this._element.width || this._element.naturalWidth,
'" height="', this._element.height || this._element.height,
```

second line doesn't seem to be correct

**Comment by asturur** [comment]
yep is not.

**Comment by kephin** [comment]
@asturur Any update for #4736 ? Or is there anything I can do? Thanks.

**Pull request merged**
