### PR TITLE
Add letter spacing support for svg

### PR DESCRIPTION
**Pull request by AvaelKross**
This adds a support for letter spacing in exported svg files. Also I fixed the parser to set charSpacing according to letter-spacing css rule. I have no time to make sure test works, so please feel free to improve it. I tested it manually for iText, and it works like a charm and keeps positioning very accurately.

### CODE REVIEW

**Comment by asturur** [comment]
i did not even know letter-spacing was a SVG thing.

I have to check the SVG export, but looks good overall

**Comment by asturur** [comment]
image

this Canvas text can be actually be exported like this in the SVG

image


how your changes will influence the Itext export? can you post some simple screenshot?

**Comment by AvaelKross** [comment]
hmm.. this is a sample itext object on canvas:

and this is an svg version:

(ignore sizing etc., these was just differently cropped)

**Comment by asturur** [comment]
i guess the itext code needs to be cleared from the actual charspacing code and left your one

**Comment by asturur** [comment]
i think this has been solved with latest master. Anyway since the new text changes, the svg ouput must be handled differently

**Comment by asturur** [comment]
@AvaelKross more than one year passed, but @brentcappello made me notice today that here there was some unmerged work. So i cleaned it up and merge it.

**Pull request merged**
