### PR TITLE
Fix stroke width calculation

### LINKED ISSUE #2177: mouse scaling bug
A scaling by mouse might have a bug.

The scaled size of Line is twice larger than a expected size. The strokeWidth of object might cause this size difference.

http://jsfiddle.net/sapics/tt5zjjot/1/

ezgif com-gif-maker 1

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/13389170-mouse-scaling-bug?utm_campaign=plugin&utm_content=tracker%2F23217&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F23217&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by sapics**
From #1929, strokeWidth calculation dose not depends on stroke.

closes #2177

### CODE REVIEW

**Comment by asturur** [comment]
I definitely missed this.
Inspecting for #2177 i noticed that, and i was about to fix this.

**Comment by sapics** [comment]
@asturur i found it from #2177, too!

**Comment by asturur** [comment]
Sapics if you remove the half part of strokewidth, and you scale will FULL strokewidth in both _setObjectScale  and _scaleObjectEqually, you will notice that #2177 is fixed.
For the third function you modified check if apply.

Obviously if we are doing something with width, we cannot just use half of stroke.
For vLine and hLine still some tweak is necessary.

Could you make that? if i do this we will have conflicting PR

**Comment by sapics** [comment]
Absolutely!
I have not understood about definition of localMouse yet, thus, I cannot judge HALF or FULL strokeWidth is right.
It would be better to close this PR to avoid conflict.

**Comment by asturur** [comment]
I think this PR is good, let's just finish it.
Exactly where you changed the strokeWidth definition, if you remove the use of strokeWidth / 2 and use strokeWidth, the object scaling is fixed 99% of time.

localMouse  depends on the translate ( s) function, there are at least 3, and the fix is ugly as shit for them.
the fix would be:
```
          vLine = target.type === 'line' && target.width === 0,
          hLine = target.type === 'line' && target.height === 0,
          strokeWidthX = hLine ? 0 : target.strokeWidth,
          strokeWidthY = vLine ? 0 : target.strokeWidth;
```
and use strokeWidthX and strokeWidthY for the x and y instead of general strokeWidth.

If you try to resize this in current kitchensink on fabricJS.com:
```
canvas.add(new fabric.Rect({
 width:50, height:50,
      fill: 'red',
      stroke: 'blue',
      strokeWidth: 20
}))
```

You will notice that is wrong.
So the scaling function we have is just wrong, no one notice because large strokeWidth is not so popular.

**Comment by asturur** [comment]
@sapics thanks!

Can you also rebase the commit to have them nice?

**Comment by sapics** [comment]
@asturur I am sorry, I misunderstood you wrote.
I create jsfiddle to check this fix.
PREVIOUS: http://jsfiddle.net/sapics/tt5zjjot/8/
THIS PR: http://jsfiddle.net/sapics/tt5zjjot/7/

**Comment by sapics** [comment]
Sure!!

**Comment by asturur** [comment]
To fix the "translate effect" that still remain for just horizontal or vertical lines i would wait.

We should spam this code 
```
          vLine = target.type === 'line' && target.width === 0,
          hLine = target.type === 'line' && target.height === 0,
          strokeWidthX = hLine ? 0 : target.strokeWidth,
          strokeWidthY = vLine ? 0 : target.strokeWidth;
```
All around the functions, while i want to do something more clean.
@kangax i think you can merge this after a quick look.

**Comment by sapics** [comment]
Is it better or not?
```javascript
vLine = target.type === 'line' && target.width === 0,
hLine = target.type === 'line' && target.height === 0,
sLine = vLine || hLine,
capped = target.strokeLineCap === 'round' || target.strokeLineCap === 'square',
strokeWidthX = ((capped && hLine) || !sLine) ? target.strokeWidth : 0,
strokeWidthY = ((capped && vLine) || !sLine) ? target.strokeWidth : 0;
```

**Comment by sapics** [comment]
@asturur Thank you! I have fixed as you coded and rebase!

**Comment by kangax** [comment]
Awesome, thanks. Don't forget changelog please.

**Pull request merged**
