### PR TITLE
Switch the ocoords system for groups

### PR DESCRIPTION
**Pull request by asturur**
This PR aims at setting oCoords of grouped objects without the zoom of canvas.
In this way the zoom is not applied once for nesting level and normalizing the pointer is easier.

### CODE REVIEW

**Comment by samael205** [comment]
Hi @asturur , this commit solves the problem of the coordinates of the groups when selecting programmatically.

I explain what I do:

What I do is that when the load canvas, select all objects on the canvas, creating a group. From that group, to obtain the boundingBox, and go zooming in or zoom out so that the elements conform to the width and height of the canvas.

Currently only I can do this, if pre-select all items with the mouse

Regards!

**Comment by asturur** [comment]
yes but it needs more changes and controls. is not ready yet. i m finishing object caching before.

**Comment by samael205** [comment]
Ok, I will be patient

**Comment by samael205** [comment]
@asturur Hi, I have a another question referenced by this PR.

Is it possible that the top and the left of the copy in groups are also badly calculated?

**Pull request closed without merging**
