### PR TITLE
Allows setting origin to any value between 0(top/left) and 1(bottom/right)

### PR DESCRIPTION
**Pull request by virror**
I have been using this for quite a while at work with our current project and seems to work fine. Sometimes you need to be able to set another origin that just the predefined ones and then this is perfect. No issues with backwards compatibility, just adds on top.

### CODE REVIEW

**Comment by asturur** [comment]
If is just this change, i m happy to include it. (style needs fixes)
But i see those functions that does direct use of originX and originY using comparing center , left and right:

_resetCurrentTransform
_setLocalMouse
_flipObject

**Comment by virror** [comment]
Ok, thank. Will have a look at the style and those 3 functions.

**Comment by virror** [comment]
@asturur Ping!

**Comment by asturur** [comment]
i watched the code a couple of time and i think made you change that other
functions for no reason.

i need to download it and try, i very busy those days.

**Comment by virror** [comment]
I just did as you said : p
No hurry, just wanted to make sure you forgot about it.

**Comment by virror** [comment]
Don't forget, lol

**Comment by asturur** [comment]
merged in a temporary branch so i can do tests.

**Comment by asturur** [comment]
@virror i had to do some corrections, there were errors.
I would like to pull your work anyway.
If you have time take #3121 and make a merge  over your branch of my changes.
Basically:
canvas.class.js needs to have no changes, those functions i asked you to check did not need for changes.
You left some syntax error in src/mixins/object_origin.mixin.js file
And some logic error in the function AdjustPosition(to).

If you can delete the changes in canvas.class.js and fix the errors in src/mixins/object_origin.mxin.js i will merge your PR. otherwise i will pull #3121 that is ready.

**Comment by asturur** [comment]
When you open a PR you have to check that
npm run build and npm run test run correctly.

**Comment by virror** [comment]
@asturur Maybe its easiest for you to just pull your branch since it has all the tests and stuff as well?
For me it does not really matter : )

**Comment by asturur** [comment]
ok i just wanted to give you credit for the contribution. i pull the other.

**Pull request closed without merging**
