### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by asturur**
Try to fix build test

### CODE REVIEW

**Comment by asturur** [comment]
@kangax, this fixes the tests on the new infrastructure.
Can you please merge this?

**Comment by kangax** [comment]
I'm on a phone so feel free to merge!

**Comment by asturur** [comment]
merge from phone!

**Comment by asturur** [comment]
merge from phone!

**Comment by asturur** [comment]
merge from phone!

**Comment by asturur** [comment]
had some problem with phone.....

**Pull request merged**
