### PR TITLE
support for general transform matrix and ungrouped svgs 

### PR DESCRIPTION
**Pull request by asturur**
not to merge yet.
need help with testing.
add more notes later

### CODE REVIEW

**Comment by asturur** [comment]
@sapics can we talk about this mods, without spamming on github? can i have your email? or you can contact me on skype ( andreatax contact ). As you wish, if you wish.

**Comment by sapics** [comment]
@asturur Sure! At 21th April, I sent my email to your email. You could not get it?

**Comment by sapics** [comment]
I am sorry, i will go out soon, today.

**Comment by asturur** [comment]
I did not get your email, i checked now.
my email is andreabogazzi79@gmail.com

**Comment by sapics** [comment]
I send mail now. Please check!

**Comment by asturur** [comment]
reference svg for rotate matrix on transform matrix

probably is not enought to transform dimensions, but we have to transform 4 points of the object and calculate a boundingbox.

image

```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 17.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 1000 1000" width="1000" height="1000" xml:space="preserve">
<rect transform="skewX(45)" fill="blue" width="100" height="100" ></rect>
<rect transform="skewX(45)" fill="red" width="100" height="100" x="0" y="60" ></rect>
<rect transform="skewX(45)" fill="green" width="100" height="100" x="0" y="120"></rect>
<rect transform="skewX(45)" fill="yellow" width="100" height="100" x="0" y="200"></rect>
<rect transform="rotate(33)" fill="blue" width="100" height="100" ></rect>
<rect transform="rotate(33)" fill="red" width="100" height="100" x="0" y="60" ></rect>
<rect transform="rotate(33)" fill="green" width="100" height="100" x="100" y="120"></rect>
<rect transform="rotate(33) skewX(45)" fill="purple" width="100" height="100" x="400" y="100"></rect>
<rect transform="skewX(45) rotate(33)" fill="purple" width="100" height="100" x="400" y="100"></rect>
</svg>
```

**Comment by asturur** [comment]
Optimized getNonTransformedDimensions as per @sapics suggestion.
Less code and simpler to read.

**Comment by sapics** [comment]
add a test case for mouse interaction in http://jsfiddle.net/sapics/tt5zjjot/25/
ezgif com-optimize

**Comment by asturur** [comment]
thanks!
i do not think that this pr can solve even that problem.

there is a problem of ungrouping and applying he correct transform to every object.

probably this will come out with skew support that is immediately after this pr ( in my mind, then who knows)

i do not want make this pr too big i want just to handle an object with generic transform as any other object.

**Comment by sapics** [comment]
Oh, sorry.
I just guess that this bug looks similar with this PR `transform 4 points of the object`.
After this PR, this bug might fix easier.

Is it better to make an issue about this bug for remember?

**Comment by asturur** [comment]
Added correct bounding box for object that contains a rotation matrix.

**Pull request closed without merging**
