### PR TITLE
Make toJSON/toSVG behave sensibly with an active selection group

### PR DESCRIPTION
**Pull request by KJTsanaktsidis**
Calling toJSON or toSVG on a canvas whilst there is an active selection group causes it to be destroyed & recreated. This causes a number of nasties to happen, as described in https://github.com/kangax/fabric.js/issues/1876. This PR changes the way these methods work to avoid needing to do this; instead of realising the result of the group's transform on its objects by destroying the group, the group gains a method for doing this explicitly, and toJSON/toSVG pass clones of selected objects into this method.

This is a version of @slashgrin's fiddle including this patch, demonstrating that the problem has gone:
http://jsfiddle.net/2yy2t5nw/6/

These fiddles verify that toJSON/toSVG seem to be doing the right thing:
http://jsfiddle.net/2yy2t5nw/7/
http://jsfiddle.net/zsc1p82w/8/

### CODE REVIEW

**Comment by KJTsanaktsidis** [comment]
It looks like calling clone while doing toJSON/toSVG is a bad idea for async objects. The solution seems to be to mutate and then restore the actual object being serialized.

**Comment by KJTsanaktsidis** [comment]
@kangax @asturur I'd love some feedback on this PR- is what I've done here a good idea or does it need some improvement?

**Comment by kangax** [comment]
@KJTsanaktsidis sorry, didn't have time to look through this yet. Will do soon!

**Comment by KJTsanaktsidis** [comment]
It turns out that since the group calls `set()` on the object to apply the relevant transforms, when these transforms are unwound, `set()` should also be called. This ensures that if you are watching any properties by overriding `set`, you see that the group transform gets undone.

**Comment by kangax** [comment]
I like the idea and the implementation! Docs look good too. Thanks @KJTsanaktsidis, merging.

**Comment by kangax** [comment]
Btw, I don't remember if we have tests for this functionality; if we don't, would be awesome to add a few.

**Pull request merged**
