### PR TITLE
Set default value of strokeDashArray so that SVG is valid

### PR DESCRIPTION
**Pull request by sorich87**
When `strokeDashArray` is not set on an object, it's rendered in the SVG as `stroke-dasharray: ;`, which breaks some parsers.

This PR fixes it so that the default value `none` is used.

### CODE REVIEW

**Comment by kangax** [comment]
Thanks! Could you please fix unit test as well.

**Comment by sorich87** [comment]
Done.

**Comment by asturur** [comment]
There was an old pr that i never finished to export just NON default values into svgs.
While this is a simple fix to merge and fix asap if it breaks some parsers, with mind term thinking we should avoid to export all the properties that are default svg value ( black color, strokewidth = 1, opacity = 1.... and so no) 
@sorich87 wich parser where you using?

**Comment by sorich87** [comment]
It was PHP xml parser, and I think librsvg too.

**Pull request merged**
