### PR TITLE
change way for mousemove when freedraw,O(n) => O(1) 

### PR DESCRIPTION
**Pull request by boomyao**

### CODE REVIEW

**Comment by asturur** [comment]
We have a problem here,
_render needs to be able to redraw everything if needed.
If you want to draw just one segment at time, look at how the other brushes works ( circleBrush i believe is a good example)

**Comment by boomyao** [comment]
i see, i add _curPointIdx at "_reset" func record the next point index and do away with clear canvas context  mousemove, i try to use circleBrush, it's still work.

**Comment by asturur** [comment]
@boomyao did you understand my comment, and can you update the PR?

**Comment by asturur** [comment]
Where is the old code was actually good, we just need to understand each other.

**Comment by asturur** [comment]
What we need to do is split the render method in 2 functions, one able to render a single segment, another able to render everything, for compliance with the library.
I probably failed in comunicating this to you. lets reopen this PR and fix it. I'll help

**Comment by boomyao** [comment]
sorry, my english is so poor.
i add a new pr #4743

**Comment by asturur** [comment]
I see the new PR, but this was better.

**Comment by boomyao** [comment]
no......  fine, i will back to this PR.

**Comment by boomyao** [comment]
hi! i have updated at #4743

**Pull request closed without merging**
