### PR TITLE
trying to fix travis

### PR DESCRIPTION
**Pull request by asturur**
making some try and catch i got this:

```
at /home/travis/build/kangax/fabric.js/node_modules/jscs/lib/rules/require-multiple-var-decl.js:8:24
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (/home/travis/build/kangax/fabric.js/node_modules/jscs/lib/js-file.js:322:42)
    at Object.consecutive [as _check] (/home/travis/build/kangax/fabric.js/node_modules/jscs/lib/rules/require-multiple-var-decl.js:4:10)
    at Object.module.exports.check (/home/travis/build/kangax/fabric.js/node_modules/jscs/lib/rules/require-multiple-var-decl.js:86:28)
    at null.<anonymous> (/home/travis/build/kangax/fabric.js/node_modules/jscs/lib/string-checker.js:110:22)
    at Array.forEach (native)
    at StringChecker.checkString (/home/travis/build/kangax/fabric.js/node_modules/jscs/lib/string-checker.js:108:35)
    at null.<anonymous> (/home/travis/build/kangax/fabric.js/node_modules/jscs/lib/checker.js:40:25)
    at Array.7 (/home/travis/build/kangax/fabric.js/node_modules/jscs/node_modules/vow/lib/vow.js:699:39)
```

I verified on jscs github there is a recent issue with this error.
Restoring back the jscs to the 2.7.x branch solves our issue.

It looks like that   io.js  is supported from NVM 23.0. we have 0.20
If we want to have green thick, i can suggest just this change and wait for travis to update.
Otherwise in the before-script we can try to update nvm or something else if we really need io.js environment testing now.

### CODE REVIEW

**Comment by asturur** [comment]
@kangax have a look at that PR.
Discard it or pull it.
This is only way i found to restore the travis "green tick".

**Comment by kangax** [comment]
Does it work with jscs 1.7 AND io.js?

**Comment by asturur** [comment]
no i tried even that. all red cross.
Il 20/gen/2015 19:34 "Juriy Zaytsev" <notifications@github.com> ha scritto:

**Comment by kangax** [comment]
Hm, oh well.. ok, merging. Thanks for investigating, Andrea.

**Comment by asturur** [comment]
we will add later as soon as we know travis is supporting io.js

**Pull request merged**
