### PR TITLE
Control customization part 2 - Allow for separate corner filling and cornerStroke

### PR DESCRIPTION
**Pull request by asturur**
- add CornerStrokeColor property
- default behaviour with transparentCorners does not change ( for people loading json created before or overriding classes with just cornerColor and transparentCorner = true );

### CODE REVIEW

**Comment by asturur** [comment]
image

**Comment by taqimustafa** [comment]
Is it possible to have the option to change the rotation handle position, The default position is top, but if we want to show it at the bottom of the Object ?

**Comment by asturur** [comment]
```javascript
       if (this.hasRotatingPoint) {
         this._drawControl('mtr', ctx, methodName,
           left + width / 2,
           top + height + this.rotatingPointOffset);
       }
```

you should override the function that has this snippet with another that is same content but with the hasRotatingPoint part changed like i did

**Comment by taqimustafa** [comment]
Also can we make the borders dashed ? something similar to the attached image ? 
screenshot_35

**Comment by taqimustafa** [comment]
i found a way by adding `ctx.setLineDash([3,2]);` in drawBorders function, but i was hoping if there is anyway we can do that directly ?

**Comment by asturur** [comment]
http://fabricjs.com/fabric-changelog

check borderDashArray

**Pull request merged**
