### PR TITLE
fix for null shadow

### PR DESCRIPTION
**Pull request by sapics**
This PR fix error `Uncaught TypeError: Cannot read property 'affectStroke' of null`

### CODE REVIEW

**Comment by asturur** [comment]
ok this is my fresh error of yesterday.
so dumb.

i m sorry i did not use stroke on my tests. will be more carefull.

**Comment by asturur** [comment]
i removed it because inside the remove shadow function we do the same check again.

**Comment by asturur** [comment]
@sapics sorry i have to submit 2 PRs both conflicting with this.
I copy your fix in my PR for text and for object class, otherwise is complicated to merge

**Comment by sapics** [comment]
@asturur I see! Is it better to close?

**Pull request closed without merging**
