### PR TITLE
Fix rendering justified text with line breaks and last line

### PR DESCRIPTION
**Pull request by pavelKozlov**
Here is a linked issue: https://github.com/kangax/fabric.js/issues/3444.

The problem is that text with textAlign == 'justify' also stretches lines with line breaks and the last line in text, but these lines should be rendered as left aligned.

### CODE REVIEW

**Comment by asturur** [comment]
I see some problem here: in Itext all lines are with break, so justify will stop working?

**Comment by pavelKozlov** [comment]
Are you sure? I tested it on class that extends fabric.Textbox in project that I'm working on and it works like a charm.
I get line breaks using `this.text` split by `_reNewline` and compare it to `_textLines`.

**Comment by asturur** [comment]
does it work on simple.ITEXT class?

**Comment by pavelKozlov** [comment]
I think, if text with text align justify has every line contains line break, it should be render as left-aligned.
That's how it acts in text editor such as Word or Google Docs.

**Comment by asturur** [comment]
yes but this is out it always worked here. i do not want to change this since application depends from it. i m ok with last line not being justified but if we insert a sort of paragraph meaning to the hard newline is too much change.

**Comment by pavelKozlov** [comment]
But that's how justify works. What if use decide to add text with a few paragraphs?
Anyway, it's up to you to decide.
Last line is also improvement.
Please, let me know if I need fix to work only for last line.

**Comment by pavelKozlov** [comment]
@asturur, I have changed code to left align only last line in justified text.

**Comment by asturur** [comment]
sorry to let pass all this time.
I realize now we do not have svg export functionality for this.
You can add or i will add as soon as i can

**Comment by jilster** [comment]
See https://github.com/kangax/fabric.js/pull/4441

**Pull request closed without merging**
