### PR TITLE
switch to eslint

### PR DESCRIPTION
**Pull request by asturur**
not working for now.
converted configuration files with tool.

### CODE REVIEW

**Comment by asturur** [comment]
Main things to fix are:
one-var declaration, remove extra space between square brackets,  fix some indent case.

After all this taking down jsdocs that are most of the failures ( now disabled ).

**Comment by asturur** [comment]
@neopheus  if you have will to help, this is just about fixing spaces and indent. If no sure about some rules ask.
I know this is a boring job

**Comment by neopheus** [comment]
no pb
i do it ;)

**Comment by asturur** [comment]
pick up some files, let me.know wich, i ll work on other, so we do not steps on our feets

**Comment by asturur** [comment]
fixed util/misc.js

**Comment by asturur** [comment]
removed space in square bracket in all files

**Comment by asturur** [comment]
disabled one-var, down to 79 failures

**Comment by asturur** [comment]
Some comparison with stricit equal probably killed some functionalities. if i cannot find it i will revert changes.

**Pull request merged**
