### PR TITLE
Update Wheel event

### PR DESCRIPTION
**Pull request by neopheus**
Demo with new code : https://jsfiddle.net/bzd6888b/3/

### CODE REVIEW

**Comment by asturur** [comment]
What was the problem with old code? i want to rely on event.js as little as possible.

**Comment by neopheus** [comment]
With the old code the event does not work (test On Firefox 47 Windows + Chrome 52)

Example with bug : https://jsfiddle.net/bzd6888b/5/

**Comment by asturur** [comment]
image

it looks like the wheel event is standard. Why rely on event.js?

**Comment by neopheus** [comment]
Actually in the code : https://github.com/kangax/fabric.js/blob/fd6038d50d4b32f2b43448fef1b8b4b3ba996432/src/mixins/canvas_events.mixin.js#L46

We use "mousewheel" event, in the Mozilla documentation : https://developer.mozilla.org/en-US/docs/Web/Events/mousewheel

**Comment by neopheus** [comment]
New version Mouse Wheel Event without event.js

**Comment by asturur** [comment]
this i will check carefully. it looks strange that we have mousewheel broken and no one complains.

**Comment by neopheus** [comment]
yes it's strange
With the new code, we don't use Event.js ;)

**Pull request merged**
