### PR TITLE
make Modifier keys customizable

### LINKED ISSUE #2680: Make it possible to select modifyer key
Currently the user are forced to use shift as the modifier key when selecting multiple objects as an example. It would be nice if this could be set in the canvas, for example canvas.set(modifierKey, "CRTL") or something.

### PR DESCRIPTION
**Pull request by asturur**
@VictorHagsand i made up this based on #2680.
No added code, just properties. It may be cool.

closes #2680

### CODE REVIEW

**Comment by VictorHagsand** [comment]
Very cool, thank you!
Saves us a bunch of overrides : )

**Comment by asturur** [comment]
yes you have to override 5 functions to change all keys.

**Comment by VictorHagsand** [comment]
Yupp, did that already before i made this suggestion here, thought that it might be useful for other people as a standard feature. I assume this will get merged later?

**Comment by asturur** [comment]
i have to be sure it works good. did not try yet.

**Pull request merged**
