### PR TITLE
Improve Object selection - Fix Line shape toObject

### PR DESCRIPTION
**Pull request by farnabaz**
Let canvas select a selectable objects that exists under a none-selectable Object by only processing selectable objects

### CODE REVIEW

**Comment by sapics** [comment]
@farnabaz Is there a example (like jsfiddle) which causes problems by calling `calcLinePoints` in `toObject`?

**Comment by farnabaz** [comment]
@sapics here is example for first commit http://jsfiddle.net/o48qeepu/
and for second commit, i'll try to create a proper example, but to explain the problem: this issue occurs when I'm trying to create socket base canvas app using fabric, and when I send `toJSON()` value to another user over socket, created Line on receiver canvas is in different position from sender

**Comment by sapics** [comment]
@farnabaz Thank you for jsfiddle and explanation!
For the second commit, it reverts a part of #1714. It would be necessary to demonstrate a bug.

**Comment by asturur** [comment]
i understand the bug, i will put up a test to demonstrate it.

**Comment by asturur** [comment]
Regarding to line object:
http://jsfiddle.net/xvzms0j6/34/
Please try to make a jsfiddle with bug, from this jsfiddle it looks like is working good.

**Comment by sapics** [comment]
@asturur Thank you for jsfiddle!
I also confirmed that working well, with moving, scaling, rotation.

**Comment by farnabaz** [comment]
I try to create jsfiddle to show bug, but in all attempts I fail
here is my work (fabric.js on socket.io), the idea is to observe `object:added` `object:modified` .. and send these events over socket and create/update object in client side, this has server & client, and only server could draw 

server: http://nodejs.moror.ir/server.html
client: http://nodejs.moror.ir/

- open server & client in two window
- press `L` and drag to draw line

as you see in client side line position is different from server side, but when iill change `Line.toObject` method lines are in same position

**Comment by asturur** [comment]
I see.
I'm sorry but we still need a simple test case to replicate the bug and accept the PR or propose another solution.
We need to replicate it in a simple js script or in a nodejs setup where we can see the code.

http://jsfiddle.net/xvzms0j6/34/

Can you not make it happen in that jsfiddle?

**Comment by farnabaz** [comment]
look at this jsfiddle: http://jsfiddle.net/xvzms0j6/36/

**Comment by farnabaz** [comment]
@asturur Thank you, It works so well
but I think this is a little confusing, because `set` function works well for other shapes

**Comment by asturur** [comment]
I think is a coincidence.
toObject and fromObject are created for other reasons.
But as you noticed, what you where doing  is just passing the value of properties as they are, without any modification ( so instaed of calcLinePoints, just the four points ).

So you can create your own method "toSimpleObject", to do just what you need. 
So passing each property or a subset of them, to an object, that later you use with "set" method.

**Pull request closed without merging**
