### PR TITLE
Update path.class.js

### PR DESCRIPTION
**Pull request by by12**
Bug Fixed Request. Can you please fixed a small bug in path class.

### CODE REVIEW

**Comment by asturur** [comment]
Sorry i missed this PR.
What the bug fixes? i would be super happy to merge it if i know what does it change.
Any screenshot available?

**Comment by by12** [comment]
Hi,
    Only the problem here is you are using to time the same x and y. But normally for the Bezier Curve we need the  fabric.util.getBoundsOfCurve( x, y,  current[1],  current[2],  current[3],  current[4],  current[5],  current[6]);

But in your case you have 
x = current[5];
y = current[6];
controlX = current[3];
controlY = current[4];

and then fabric.util.getBoundsOfCurve(x,  y,  current[1],  current[2] ,  controlX,  controlY,  x,  y);
so its mean you always have the same start and end points.   current[5],  current[6],
  
fabric.util.getBoundsOfCurve(current[5],  current[6],  current[1],  current[2],  current[3],  current[4],  current[5],  current[6]);

which is making problems

**Comment by asturur** [comment]
ohhh this could be the error i was searching for so long!!!!!

any idea why on the left screenshot the curve do not touch the left side of the bbox?

**Comment by by12** [comment]
Hi,
   Screen shots were from quick and dirty modifications. space on left side was some thing else not because of fabric. There are new screen shot with fabric 1.7.8.
untitled
 
So everything looked fine now. 
Have a nice day

**Pull request merged**
