### PR TITLE
Added the overlay blending method

### PR DESCRIPTION
**Pull request by khawerrind**
Overlay: Multiplies or screens the colors, depending on the base color. Patterns or colors overlay the existing pixels while preserving the highlights and shadows of the base color. The base color is not replaced, but mixed with the blend color to reflect the lightness or darkness of the original color.

### CODE REVIEW

**Comment by asturur** [comment]
Thanks, i was about to ask you to make a correct pr. I will check it

**Comment by khawerrind** [comment]
@asturur yes it was my fault. I have corrected it now. Thanks for checking.

**Comment by asturur** [comment]
Just to add that i noticed the PR is good, but i need/want to personally check some reference to see that the "overlay" blending mode exist and does what you did.
Then we can merge it or at least correct it.

**Comment by khawerrind** [comment]
I have created more blending methods. Should i delete this MR and create a new one?

**Comment by asturur** [comment]
not necessary, you can paste and discuss here the blending modes.
Explain us where did you take the alghoritm ( some source, some evidence that this is correct ). and then we discuss if there is need to re do another PR.

**Comment by khawerrind** [comment]
Sorry there was a mistake in the **_overlay_** method which i have corrected it. Here is the correct version & a new blending method which is **_exclusion_**

OVERLAY
```
	data[i] = tr < 128 ? (r * tr / 128) : (255 - (255 - r) * (255 - tr) / 127);

	data[i+1] = tg < 128 ? (g * tg / 128) : (255 - (255 - g) * (255 - tg) / 127);

	data[i+2] = tb < 128 ? (b * tb / 128) : (255 - (255 - b) * (255 - tb) / 127);
```
			
EXCLUSION
```
	data[i] = tr + r - ((2 * tr * r) / 255);
	data[i+1] = tg + g - ((2 * tg * g) / 255);
	data[i+2] = tb + b - ((2 * tb * b) / 255);
```

The formula reference for **_overlay_** i took from http://zhur74.livejournal.com/14839.html which is as follows 

![IMAGE]
(http://ljplus.ru/img4/z/h/zhur74/04_Overlay_Formula_8.jpg)

The formula reference for **_exclusion_** i took from http://zhur74.livejournal.com/17188.html which is as follows 

![IMAGE]
(http://ljplus.ru/img4/z/h/zhur74/24_Exclusion_Formula_8.jpg)

This guy has explained all the formulas for blending methods. We can create many other blending methods by reading his journal.

I have created a fiddle for you to test the overlay & exclusion blending methods https://jsfiddle.net/y4k380j8/

**Comment by khawerrind** [comment]
I have also tested the [GIMP](https://www.gimp.org/) **_overlay_** method and it does exactly the same. 

**Using Fabric JS Overlay Method**
![IMAGE]
(http://i.imgur.com/cNQxGbl.png)

**Using GIMP Overlay Method**
![IMAGE]
(http://i.imgur.com/BEOkfaW.png)

I was unable to remove overlay from transparent pixels in GIMP but if you open both images in new tabs you will see both are exactly the same.

**Comment by asturur** [comment]
@khawerrind i putting both overlay methods in the new filter code. thanks.

**Pull request closed without merging**
