### PR TITLE
Textbox pull request2

### PR DESCRIPTION
**Pull request by jafferhaider**
Cleaned up version of https://github.com/kangax/fabric.js/pull/1778

This PR still have changes in the /dist folder and the gestures code that's already been merged. I'm really new to github and have wasted a lot of time trying to figure out how to isolate changes for this PR. Any help will be appreciated.

A recent change has caused a but in cursor placement for Textbox. I'm working on a fix which I will commit in this branch. I just wanted to get the ball rolling in the meanwhile.

### CODE REVIEW

**Comment by kangax** [comment]
@jafferhaider have you seen whatever is under the changes tab? :)

**Comment by asturur** [comment]
it took me a bit to figure out how to send a clean pr.

i normally do like that:

i sync my master to kangax master.

i create a new branch

i commit to that branch only the files i modified or added, ignoring the other files. i do not build fabric.

optionally i do git rebase -i "last commit before mine" to give just one commit with total changes.

**Comment by jafferhaider** [comment]
Ah ... perhaps the mistake I made was that I synced a new branch with fabricjs master. That didn't seem to work completely. Lemme try again. Sorry for being such a noob at Git! :(

**Comment by asturur** [comment]
if you do not have important branches other than your textbox, you can also delete the repo, clone again, and then add again your modification.

of course you have to have a copy before deleting.

**Pull request closed without merging**
