### PR TITLE
WIP Patternload

### LINKED ISSUE #935: Load from JSON is not working with Patterns in the latest version of Fabric.js
When am trying to load the JSON data onto the canvas, every shape is getting loaded but the patterns that are filled in the shapes are loaded only after I click on the shape.

Could some one please explain why this is happening? I even checked this:

canvas2.loadFromJSON(json,canvas2.renderAll.bind(canvas2));
Also, the same problem is with the clone() function: the object is duplicated. But the pattern filled in the object is shown only after I click on the object.

I am using version 1.3.7.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1048517-load-from-json-is-not-working-with-patterns-in-the-latest-version-of-fabric-js?utm_campaign=plugin&utm_content=tracker%2F23217&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F23217&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by asturur**
close #935

create a fromObject function that can wait for patterns in stroke and fill to be loaded.
Make all objects able to be loaded with a callback

### CODE REVIEW

**Comment by mariotacke** [comment]
This is a breaking change from 1.7.2 to 1.7.3. We had the following code:

```
fabric.Image.filters.Thresholding.fromObject = function (object) {
  return new fabric.Image.filters.Thresholding(object);
};
```

This no longer works. Is the required callback documented anywhere? I was not able to see this change via the release changelog.

**Comment by asturur** [comment]
oh well, i think you are right. for custom saved json this may be a problem. you can also return the instance for normal restoring.
I should have switched to 1.8.0 for this change at least.

i will.come back with more example and docs

**Comment by asturur** [comment]
for example the base filter fromObject will serve the purpose of any filter restore unless you have some special code.

So in your case if the Thresholding filter is of type `Tresholding`

`fabric.Image.filters.Thresholding.fromObject = fabric.Image.filters.BaseFilter.fromObject;`

would be enough.

I will add this notice in the changelog, not doing it was a fault.

**Comment by mariotacke** [comment]
I appreciate the transparency! Will adjust our code to your suggestion!

**Pull request merged**
