### PR TITLE
Fix text itext code

### LINKED ISSUE #2366: Textbox - Cursor placement when aligned right or center
I found another bug today, which I am surprised I found this late. The Textbox class has a _setLineWidths() function that gets called from _initDimensions(). However, the line widths it sets are very different from the ones that get calculated in _getLineWidth(). This effects the cursor placement when the text is aligned to the center, or to the right.

I will submit a PR that just removes setting _setLineWidths(), that way it can be lazily cached by getLineWidths().

@jafferhaider does that sound right?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/25038098-textbox-cursor-placement-when-aligned-right-or-center?utm_campaign=plugin&utm_content=tracker%2F23217&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F23217&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by asturur**
Removed _getSVGLineLeftOffset:
It was just calling getLineLeftOffset and was executing "tofixed, 2" on it.

Later the result was exported to svg, adding another number with arbitrary precision and toFixed was not executed again.

Removed direct access to this.__lineWidths[i].

Removed _getCachedLeftOffset and its caching array:
It was calling getLineLeftOffset and caching the result.
Consider that getLineLeftOffset is actually:

```
    _getLineLeftOffset: function(lineWidth) {
      if (this.textAlign === 'center') {
        return (this.width - lineWidth) / 2;
      }
      if (this.textAlign === 'right') {
        return this.width - lineWidth;
      }
      return 0;
    },
```
no need to cache it.

closes #2366

### CODE REVIEW

**Comment by asturur** [comment]
@jafferhaider  @inssein @kangax 
I have to try the build yet. If someone wants to try before me is welcome.

**Comment by asturur** [comment]
looks fixed:
quick code for copy paste in kitchensink:
```
// clear canvas
canvas.clear();

// remove currently selected object
canvas.remove(canvas.getActiveObject());

// add red rectangle
canvas.add(new fabric.Textbox('a bb ccc dddd eeeee ffffff ggggggg aa'));
```

updated kitchensink:
http://www.deltalink.it/andreab/fabric/kitchensink.html

**Comment by inssein** [comment]
looks good @asturur (haven't got time to actually try it today, but did a quick code review).

**Comment by onassar** [comment]
Amp'd to see this PR merged in. Ran into this today

**Comment by onassar** [comment]
Awesome @kangax  
What's the recommended way to get the most recent, comprehensive fabricjs?
Hotlinking from cdn at the moment, but naturally it doesn't have these changes.

**Pull request merged**
