### PR TITLE
Add browserShadowBlurConstant to adjust shadowBlur value

### LINKED ISSUE #4402: shadow doesn't render the same in chrome vs safari
## Version
2.0 beta

## Test Case
http://jsfiddle.net/7gvJG/207/

## Steps to reproduce
Check the shadow in safari vs chrome. Chrome is less blurry than Safari. From our test it seems Safari is more coherent with the same shadow props in html/CSS. 

## Safari Behavior
screen shot 2017-10-23 at 13 37 59

## Chrome Behavior
screen shot 2017-10-23 at 13 38 06

### PR DESCRIPTION
**Pull request by melvynhills**
Expose browserShadowBlurConstant to adjust shadowBlur value
close #4402

### CODE REVIEW

**Comment by asturur** [comment]
would you mind check if there are some tests of setShadow in the object tests and in case add one that demostrate that this thing works?

i can guide you.

**Comment by melvynhills** [comment]
Yeah in fact I tried to run the tests by following the Readme but when running `testem` I had errors of `QUnit` missing, although I did `npm install` and even `npm install qunit -g` 😕

**Comment by asturur** [comment]
use `npm run test`  testem is a change that got unfinished.

**Comment by melvynhills** [comment]
I get this error when running `npm run test` :

screen shot 2017-10-25 at 14 58 22

**Comment by asturur** [comment]
remove that npm install quint -g that you did before and reinstall fabric?

**Comment by melvynhills** [comment]
What do you mean by "reinstall fabric" ?
What I did:
- `npm uninstall qunit -g`
- `rm -rf node_modules`
- `npm install`
- `npm run build`
- `npm run test`

=> Still have the same error.

Then I just tried to patch QUnit with `QUnit.ok = QUnit.assert.ok.bind(QUnit.assert);`, that kinda worked but then I get another error (maybe the one caught by QUnit in the first place) :
```
{ Error: Image given has not completed loading
    at /fabric.js/test/unit/image.js:68:35
    at /fabric.js/test/unit/image.js:99:21
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:513:3) message: 'Image given has not completed loading' }
```

**Comment by melvynhills** [comment]
I see you opened a PR specifically for this, I guess it should ring a bell :)
https://github.com/qunitjs/node-qunit/pull/137

**Comment by melvynhills** [comment]
Skipped all tests but `unit/object.js` so I could run the suite, because I have errors with any test involving `fabric.Image`.

Added a simple test, tell me if it's enough. Thanks

**Comment by asturur** [comment]
If you have trouble running image tests it does me bring to think you have problem installing node-canvas.

**Comment by asturur** [comment]
test is ok, i just added descriptions so that if it fails you know what failed. if i did not broke linting i m going merge right now.

**Pull request merged**
