### PR TITLE
Add Hex Color RGBa

### LINKED ISSUE #1727: no RGBA
0xFF00FF00

alpha is a first class citizen.

new fabric.Color('#f55');
new fabric.Color('#123123');
new fabric.Color('356735');
new fabric.Color('rgb(100,0,100)');
new fabric.Color('rgba(10, 20, 30, 0.5)');

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/5076483-no-rgba?utm_campaign=plugin&utm_content=tracker%2F23217&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F23217&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by neopheus**
Add RGBa (8 digits, #FF5544CC)
https://drafts.csswg.org/css-color/#hex-notation

closes #1727

### CODE REVIEW

**Comment by asturur** [comment]
looks nice to me.
Could you please check which is the status of css3 about this color notation?

**Comment by neopheus** [comment]
For W3C/CSS : https://www.w3.org/TR/css-color-4/#hex-notation
And, for Mozilla : https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#rgba()

No more info about css3 and this color notation

**Comment by asturur** [comment]
Would you be so kind to add also the 4 digit notation? so we are complete.
I think we should pull it in.

**Comment by neopheus** [comment]
no pb ;)

**Comment by asturur** [comment]
thanks, nice PR.

**Pull request merged**
