### PR TITLE
removed this.ctx from Textbox

### PR DESCRIPTION
**Pull request by JSteunou**
backport of #4466 

#4475 should be merged first, I'll rebase if needed

### CODE REVIEW

**Comment by asturur** [comment]
i m not sure this will work. Did you test it manually?

**Comment by JSteunou** [comment]
I did not see any problems so far. Is there a reason for this change to not be able to be backported?

**Comment by asturur** [comment]
i just rememberd old text code was more couple with that this.ctx
i wanted to remove it since long, probably i did some steps and there were just some leftovers.

i ll check it and merge it

**Comment by JSteunou** [comment]
If this one has too much unknown I can close it so you can release 1.7.21

Do you want a PR for the support release?

**Comment by asturur** [comment]
just had not time to test it.
i'll do

**Pull request merged**
