### PR TITLE
Fix bugs with reflected curve path elements

### PR DESCRIPTION
**Pull request by rodovich**
```xml
<?xml version="1.0"?>
<svg width="420" height="610" viewBox="-10 0 420 610"
     xmlns="http://www.w3.org/2000/svg">

  <path d="M 0,100 l 0,-10 t 0,-40 40,-40 40,40 40,40 40,-40 40,-40 40,40 40,40 40,-40 40,-40 40,40 l 0,50 Z
           M 0,200 l 0,-10 t 0,-40 40,-40 40,40 40,40 40,-40 40,-40 40,40 40,40 40,-40 40,-40 40,40 l 0,50 Z
           M 0,300 l 0,-50 q 0,-40 40,-40 40,0 40,40 0,40 40,40 s 40,0 40,-40 80,-40 80,0 40,40 40,40 q 40,0 40,-40 0,-40 40,-40 40,0 40,40 l 0,50 Z
           M 0,400 l 0,-50 q 0,-40 40,-40 40,0 40,40 s 0,40 40,40 40,-80 80,-80 40,80 80,80 q 40,0 40,-40 0,-40 40,-40 40,0 40,40 l 0,50 Z
           M 0,500 L 0,490 T 0,450 40,410 80,450 120,490 160,450 200,410 240,450 280,490 320,450 360,410 400,450 L 400,500 Z
           M 0,600 L 0,590 Q 0,590 0,550 0,510 40,510 80,510 80,550 80,590 120,590 t 40,-40 40,-40 40,40 40,40 40,-40 40,-40 40,40 l 0,50 Z
        " fill="none" stroke="red" stroke-width="2" />

  <path d="M 0,100 l 0,-50 q 0,-40 40,-40 40,0 40,40 0,40 40,40 40,0 40,-40 0,-40 40,-40 40,0 40,40 0,40 40,40 40,0 40,-40 0,-40 40,-40 40,0 40,40 l 0,50 Z
           M 0,200 l 0,-50 q 0,-40 40,-40 40,0 40,40 0,40 40,40 40,0 40,-40 0,-40 40,-40 40,0 40,40 0,40 40,40 40,0 40,-40 0,-40 40,-40 40,0 40,40 l 0,50 Z
           M 0,300 l 0,-50 q 0,-40 40,-40 40,0 40,40 0,40 40,40 c 0,0 40,0 40,-40 0,-40 80,-40 80,0 0,40 40,40 40,40 q 40,0 40,-40 0,-40 40,-40 40,0 40,40 l 0,50 Z
           M 0,400 l 0,-50 q 0,-40 40,-40 40,0 40,40 c 0,0 0,40 40,40 40,0 40,-80 80,-80 40,0 40,80 80,80 q 40,0 40,-40 0,-40 40,-40 40,0 40,40 l 0,50 Z
           M 0,500 l 0,-50 q 0,-40 40,-40 40,0 40,40 0,40 40,40 40,0 40,-40 0,-40 40,-40 40,0 40,40 0,40 40,40 40,0 40,-40 0,-40 40,-40 40,0 40,40 l 0,50 Z
           M 0,600 l 0,-50 q 0,-40 40,-40 40,0 40,40 0,40 40,40 40,0 40,-40 0,-40 40,-40 40,0 40,40 0,40 40,40 40,0 40,-40 0,-40 40,-40 40,0 40,40 l 0,50 Z
        " fill="none" stroke="#ccc" stroke-width="4" />

</svg>
```

As rendered by Chrome:
svg-chrome

As rendered by Fabric.js:
svg-fabric

### CODE REVIEW

**Comment by asturur** [comment]
could you check if those changes should be applied also in the path boundibg box calculation? i remember is based on path commands as well.

**Comment by asturur** [comment]
sorry wrong button.

**Comment by rodovich** [comment]
@asturur I pushed a new commit making the corresponding changes in `_parseDimensions`.

**Comment by kangax** [comment]
@rodovich thanks! could you please check that all "existing" shapes still render correctly? http://fabricjs.com/test/svg_import/

**Comment by asturur** [comment]
I want to make this silly question to @kangax now that you woke me up on this code.

can we change this

```
 case 't': // shorthand quadraticCurveTo, relative

            // transform to absolute x,y
            tempX = x + current[1];
            tempY = y + current[2];

            if (previous[0].match(/[QqTt]/) === null) {
              // If there is no previous command or if the previous command was not a Q, q, T or t,
              // assume the control point is coincident with the current point
              controlX = x;
              controlY = y;
            }
            else {
              // calculate reflection of previous control point
              controlX = 2 * x - controlX;
              controlY = 2 * y - controlY;
            }

            ctx.quadraticCurveTo(
              controlX + l,
              controlY + t,
              tempX + l,
              tempY + t
            );
            x = tempX;
            y = tempY;

            break;

          case 'T':
            tempX = current[1];
            tempY = current[2];

            if (previous[0].match(/[QqTt]/) === null) {
              // If there is no previous command or if the previous command was not a Q, q, T or t,
              // assume the control point is coincident with the current point
              controlX = x;
              controlY = y;
            }
            else {
              // calculate reflection of previous control point
              controlX = 2 * x - controlX;
              controlY = 2 * y - controlY;
            }
            ctx.quadraticCurveTo(
              controlX + l,
              controlY + t,
              tempX + l,
              tempY + t
            );
            x = tempX;
            y = tempY;
            break;
```

in

```
          case 'T':
            tempX = current[1];
            tempY = current[2];

          case 't': // shorthand quadraticCurveTo, relative

            // transform to absolute x,y
            tempX += x;
            tempY += y;

            if (previous[0].match(/[QqTt]/) === null) {
              // If there is no previous command or if the previous command was not a Q, q, T or t,
              // assume the control point is coincident with the current point
              controlX = x;
              controlY = y;
            }
            else {
              // calculate reflection of previous control point
              controlX = 2 * x - controlX;
              controlY = 2 * y - controlY;
            }
            ctx.quadraticCurveTo(
              controlX + l,
              controlY + t,
              tempX + l,
              tempY + t
            );
            x = tempX;
            y = tempY;
            break;
```

Does javascript allow that? i mean case without "break;"

**Comment by asturur** [comment]
@rodovich if you wanna mirror try the tests, i can put your fabric.js here
http://www.deltalink.it/andreab/fabric/a.html
to have the tests with same shapes.

**Comment by rodovich** [comment]
I saved the HTML off the site (couldn't figure out how to build the fabricjs.com repo) and ran the python SimpleHTTPServer. I didn't notice anything broken. Here is the display for the SVG that I added in https://github.com/kangax/fabricjs.com/pull/63:

**Comment by asturur** [comment]
would you email me your fabric.js to andreabogazzi79@gmail.com so i upload it to my test and you can check all the shapes?

**Comment by kangax** [comment]
Yes, `switch`/`case` propagates through all variants if you don't `break`

**Comment by asturur** [comment]
i uploaded the fabric.js file from @rodovich  and the page at http://www.deltalink.it/andreab/fabric/a.html looks fine.

**Comment by kangax** [comment]
Cool, merging then, thanks folks!

**Pull request merged**
