### PR TITLE
Some sort of deep cloning of objects

### PR DESCRIPTION
**Pull request by asturur**
Possible fix for #2396.

Not really sure if it can break something.

### CODE REVIEW

**Comment by kangax** [comment]
Technically, this is a back-incompatible change in behavior so... this could break things in some applications, yes; we'd need to bump version. I'm not sure about changing extend to be deep clone because deep clone comes with its own problems like taking care of circular references. It's also a tad slower, which would make entire Fabric slower. lodash, for example, provides `clone` and a separate `cloneDeep` (https://lodash.com/docs#cloneDeep). One option for us would be to introduce 3rd argument — `isDeep (true | false)`, default being `false`.

**Comment by kangax** [comment]
You could see lodash taking care of circular references and other things like arguments object (which has a [[Class]] of "[object Arguments]") or host objects — https://github.com/lodash/lodash/blob/3.10.1/lodash.src.js#L1817-L1871

**Comment by asturur** [comment]
lets have as a reminder. all itext cloning and objects with transform matrix are cloned with references instead of values.
also polygon's  array of points and path commands.
group's list of objects. all referenced.

at least in toObject method of object.class,
transformatrix should be extend([], this.transformMatrix).

**Comment by kangax** [comment]
> transformatrix should be extend([], this.transformMatrix).

we can just do that for now

**Pull request closed without merging**
