### PR TITLE
Use generic setter for sourcePath

### PR DESCRIPTION
**Pull request by jparkrr**
Not completely sure if this is the right fix, but I'm pretty sure this is broken.

Thanks for all your amazing work @asturur

### CODE REVIEW

**Comment by asturur** [comment]
There is not setSourcePath function in the class? i recently moved away the named setter/getters, i may have break something

**Comment by asturur** [comment]
would you mind changing in `this.set('sourcePath', pathUrl)`  since sourcePath is something particular, i would prefer it stays wrapped in a getter in case we need to do something with it later. ( and since it was in the getter )

**Comment by jparkrr** [comment]
@asturur Thanks, updated

**Comment by asturur** [comment]
i ll merge this tomorrow after i verified why no test was failing for this error

**Pull request merged**
