### PR TITLE
Clean polygon class

### PR DESCRIPTION
**Pull request by asturur**
Remove _applyPointOffset that i introduced while ago and is totally bad.

Mainly because it change the original point array and makes difficult to add additional points to the polygon.

Need to fix SVG method.

### CODE REVIEW

**Comment by asturur** [comment]
Also there was a never triggered bug:
Points where changed in first render. But if we initialized the polygon and then executed the toSVG without going for a render, this would output a wrong polygon.

**Comment by asturur** [comment]
i noticed two unfixed shadow test. my fault.

**Comment by kangax** [comment]
> i noticed two unfixed shadow test. my fault.
so... no merge yet?

**Comment by asturur** [comment]
i uploaded the fix in some pr. maybe we just need to relaunch the tests.
Il 03/dic/2015 19:35, "Juriy Zaytsev" <notifications@github.com> ha scritto:

**Comment by asturur** [comment]
we have 3 failing tests:

this from opacity pr

Module: fabric.Group Test: set objects' value should be set properly at Object.<anonymous> (/home/travis/build/kangax/fabric.js/test/unit/group.js:130:23) Actual value: 1 Expected value: 0.12345 

those failing in nodejs but not in browser.

Module: fabric.Group Test: test group transformMatrix at Object.<anonymous> (/home/travis/build/kangax/fabric.js/test/unit/group.js:524:11) Actual value: true Expected value: false 


Module: fabric.Group Test: test group transformMatrix at Object.<anonymous> (/home/travis/build/kangax/fabric.js/test/unit/group.js:528:11) Actual value: true Expected value: false

**Comment by asturur** [comment]
any thought on this?

**Pull request merged**
