### PR TITLE
Fix textarea focus bug when canvas is in an element that stops events from reaching the body

### PR DESCRIPTION
**Pull request by kghandi**
When using bootbox to create a modal dialog, the dialog has a tabindex=-1 to prevent focusing on items outside of the dialog. Therefore the hiddenTextArea must be inside the dialog to be able to get focus.

See example: https://jsfiddle.net/kghandi/jhd6xn4x/

### CODE REVIEW

**Comment by asturur** [comment]
can you verify that internet explorer 10 and 11 can still copy paste good?
There was a problem for which we were keeping the textarea on the body.

**Comment by asturur** [comment]
Other than that calcTextArea position is written to consider body position not canvas container

**Comment by kghandi** [comment]
I just create a 2nd fiddle to point to my patched version so we can test.

kangax version: https://jsfiddle.net/kghandi/jhd6xn4x/
kghandi version: https://jsfiddle.net/kghandi/vcujr8no/

As far as I can tell copy/paste is working correctly in Chrome 56, Safari 10, Edge, and IE 11. I don't currently have IE 10 handy.

You are correct about the position offset being different. I can see this in the fiddle. But since the element is hidden I am not sure that this is significant.

**Comment by asturur** [comment]
is significant since you start to use composition features ( chinese, japanese, other languages )

**Comment by asturur** [comment]
you have to restore the fabricjs file to the original,
put a check before this.canvas to really check that the Itext is on some canvas.
Infact 4 tests are failing.
UpperCanvasElement is not said to be available since you could be using an Itext on an StaticCanvas, use lowerCanvasEl, the parent is the same.

**Comment by kghandi** [comment]
Thank you for the feedback. I think all the issues you pointed to are fixed.

**Comment by asturur** [comment]
check #3137 i think i have to revert this before other investigations

**Comment by philipstratford** [comment]
I'm having exactly this problem with a Bootstrap modal, but implementing the changes in this now-reverted PR don't resolve the problem for me. In fact, even the fiddle for the patched version linked above by @kghandi doesn't work for me - I'm still unable to type text in the text area in the fiddle's modal.

**Pull request merged**
