### PR TITLE
PR findTarget for issue #3063 

### PR DESCRIPTION
**Pull request by blucobalto**
PR findTarget not work whit a selected objects (activegroup). Issue: #3063

### CODE REVIEW

**Comment by asturur** [comment]
can you clear the es lint errors?

**Comment by blucobalto** [comment]
I'm sorry. How can I do?

**Comment by asturur** [comment]
click on the red cross and check description of errors

**Comment by blucobalto** [comment]
I'm sorry I am unfamiliar with this system.
Where should I check?

where-do-i-check

**Comment by asturur** [comment]
hello, sorry for the delay, busy days:
click on any of the the builds, 'node.js: 6' is ok for example, scroll down the log and read:
image

**Comment by blucobalto** [comment]
Hello,
no problem.

I'm sorry I accidentally created another "Pull Request" called "FindTarget Patch 1".
This issue is OK.
How do I delete the first "Pull Request": PR findTarget for issue # 3063?
Or tell me what is best to do.

Thanks a lot,
Blu

**Pull request closed without merging**
