### PR TITLE
export Transfor Matrix in toObject

### LINKED ISSUE #2333: Issue with serializing / deserialzing SVGs
Hi folks,

I am doing a basic serialization and deserialization test on fabric js by adding a svg like this:

    var path = fabric.loadSVGFromString(svgContent,function(objects, options) {
     var obj = fabric.util.groupSVGElements(objects, options);      
      obj.scaleToHeight(canvas.height-10)
         .set({ left: canvas.width/2, top: canvas.height/2 })
         .setCoords();
      canvas.add(obj).renderAll();
    });

Then I am using the following code to serialize the canvas and deserialize to see if I can save the state and recreate it later.

    // Test Serialization
    var json = JSON.stringify(this.state.canvas.toJSON());

    console.log(json);

    this.state.canvas.clear();

    var canvas = this.state.canvas;

    // and load everything from the same json
    this.state.canvas.loadFromJSON(json, function() {
        // making sure to render canvas at the end
        canvas.renderAll();
    });

    json = JSON.stringify(this.state.canvas.toJSON());
    console.log(json);

I have attached the output. Somehow the svg group doesn't seem to be interpreted & placed correctly. The JSON logged in both steps are identical.
before
after

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/24281162-issue-with-serializing-deserialzing-svgs?utm_campaign=plugin&utm_content=tracker%2F23217&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F23217&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by asturur**
closes #2333

Do not really know if we should export everything, but transformMatrix is crucial when exporting pathGroups.

### CODE REVIEW

**Comment by asturur** [comment]
Other proposed solution:

PathGroup.toObject changes:
```
    toObject: function(propertiesToInclude) {
      !propertiesToInclude && propertiesToInclude = [ ];
	  propertiesToInclude.push('transformMatrix');
      var o = extend(parentToObject.call(this, propertiesToInclude), {
        paths: invoke(this.getObjects(), 'toObject', propertiesToInclude)
      });
      if (this.sourcePath) {
        o.sourcePath = this.sourcePath;
      }
      return o;
    },
```

**Comment by asturur** [comment]
@kangax what do you say?

**Comment by kangax** [comment]
It's the kind of property that affects object representation (not controls or behavior) so we should definitely export it!

**Comment by asturur** [comment]
@kangax you can merge now.

All tests are passing but not this:
```
Module: fabric.Image Test: crossOrigin
toObject should return proper crossOrigin value
    at /home/travis/build/kangax/fabric.js/test/unit/image.js:182:7
    at /home/travis/build/kangax/fabric.js/test/unit/image.js:58:7
    at /home/travis/build/kangax/fabric.js/test/unit/image.js:75:21
    at fs.js:272:14
    at Object.oncomplete (fs.js:108:15)
Actual value:
undefined
Expected value:
```
This is because of the latest commit i was discussing with you.
So i'm not fixing this test as of now, waiting for you.
i still belive you introducd some breaking changes because those properties you removed ( crossOrigin, alignX, alignY and meetOrSlice are not handled by any export function anymore ).

**Pull request merged**
