### PR TITLE
fix getScrollLeftTop

### LINKED ISSUE #1821: Canvas pointer position is wrong when in a scrollable div
There is an issue when a canvas is placed in a scrollable div.  When you scroll the pointer position is off by the amount scrolled.

The issue is with the scroll value in the getPointer fn below.  If you remove the scroll.left and scroll.top values it works fine.

function getPointer(event, upperCanvasEl){
   event || (event = fabric.window.event);
   var element = event.target ||
                 (typeof event.srcElement !== unknown ? event.srcElement : null),
       scroll = fabric.util.getScrollLeftTop(element, upperCanvasEl);
   return {
     x: pointerX(event) + scroll.left,
     y: pointerY(event) + scroll.top
   };
 }

Please see the following fiddle:
http://jsfiddle.net/mcannon/6sksLp30/3/ 

Thanks,

Matt

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/5838351-canvas-pointer-position-is-wrong-when-in-a-scrollable-div?utm_campaign=plugin&utm_content=tracker%2F23217&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F23217&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by asturur**
original fiddle
http://jsfiddle.net/mcannon/6sksLp30/3/

In the fiddle there is a particular situation of fixed absolute and scrollabled divs.

modified fiddle with fabric 1.5.0 ad ovverridden function.
http://jsfiddle.net/6sksLp30/11/

Need some more testing with all the combination of scrollable div absolute and fixed position.

closes #1821

### CODE REVIEW

**Comment by asturur** [comment]
https://github.com/kangax/fabric.js/pull/2128

i added more complex scroll option and simpler function. it works good

**Comment by asturur** [comment]
after a brief discussion in #1821 i think we can merge this.

**Comment by kangax** [comment]
We need a failing test in misc/position

**Comment by asturur** [comment]
In the fabricjs.com?

I can replicate this if needed:
http://jsfiddle.net/asturur/7fsw81mp/5/ 
is enought small now

**Comment by kangax** [comment]
Yep, on fabrics.com. Just so that we can have a full set of functional tests to makes sure scrolling and all the other cases work.

**Comment by asturur** [comment]
cannot wait to play with jekyll again.... :sake:

**Comment by asturur** [comment]
to reproduce same problem i need an iframe, is this ok for you?

**Comment by kangax** [comment]
of course :)

**Comment by asturur** [comment]
https://github.com/kangax/fabricjs.com/pull/84

Here is PR with test for it, it is failing actually.

**Comment by kangax** [comment]
+changelog

**Pull request merged**
