### PR TITLE
Fix path group toSvg method.

### LINKED ISSUE #1838: OriginX and originY ignored when using toSVG with path groups
I already found some opened issue threads with toSVG but not clear if this is mentioned.

When using a path group with originX/originY=center and exporing the canvas with toSVG, the origin is ignored. Its working with text and images. Add this to kitchen sink:
```
// clear canvas
canvas.clear();

fabric.loadSVGFromURL('http://fabricjs.com//lib/tiger2.svg', function(objects, options) {
						var svgGroup = fabric.util.groupSVGElements(objects, options);
canvas.add(svgGroup);
svgGroup.set({ left: 300, top: 300, originX: 'center', originY: 'center'})
canvas.renderAll();

var w = window.open('', 'blank');
w.document.body.innerHTML = canvas.toSVG();

//this is working
//w.document.body.innerHTML = '<img src="'+canvas.toDataURL()+'" />';
					
});
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/6191994-originx-and-originy-ignored-when-using-tosvg-with-path-groups?utm_campaign=plugin&utm_content=tracker%2F23217&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F23217&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by asturur**
now respect current originX and originY

closes #1838

### CODE REVIEW

**Comment by kangax** [comment]
Do we have tests for this?

**Comment by asturur** [comment]
No. we do not, but we are making one.

**Comment by kangax** [comment]
Excellent :)

**Comment by asturur** [comment]
Simple test added.

**Comment by kangax** [comment]
Great, thanks @asturur

**Pull request merged**
