### PR TITLE
Add active instance cleaning to dispose.

### LINKED ISSUE #2701: `dispose` should clear `activeInstance`
If it doesn't (current state), the last instance is always leaked even after disposed and removed.

### PR DESCRIPTION
**Pull request by asturur**
closes #2701.

Still i do not get what this activeInstace does.
It is a reference to last initialized canvas.

But what is its purpouse?

### CODE REVIEW

**Comment by kangax** [comment]
Yep, last initialized one. Now that I think about it, it perhaps does seem unnecessary...

**Comment by asturur** [comment]
To me it looks unnecessary.
Maybe it was a try to do not create a global variable to access the canvas?

I would just trash it.

**Comment by kangax** [comment]
I agree. I'm all for removing unnecessary crap.

**Comment by asturur** [comment]
@kangax you can merge

**Pull request merged**
