### PR TITLE
Support HTTPS with different ports not just 443

### PR DESCRIPTION
**Pull request by earlyster**
We would like to make this change to support HTTPS running on different ports other than 443 since user may have 443 used for something else on their machine. 

Thanks,

Justin

### CODE REVIEW

**Comment by kangax** [comment]
Cool, but shouldn't it be indexOf() > -1?

**Comment by kangax** [comment]
Will fail if index == 0 afaics

**Comment by earlyster** [comment]
Trying to show someone how to use github forking and code at same time. Fixed condition to ===0 for https.

**Comment by kangax** [comment]
Thanks! :)

**Pull request merged**
