### PR TITLE
Added simple color animation utility.

### PR DESCRIPTION
**Pull request by ChrisBuergi**
A simple color animation utility using the existing animation utility.

### CODE REVIEW

**Comment by kangax** [comment]
Nice and thanks!

I made a simple demo just to see it in action (requires browser that supports input[type=color]) — http://jsfiddle.net/vZrg9/26/

I would wanna make a better demo to put on fabricjs.com (maybe bunch of rectangles stacked together like mosaic and when you hover them, they change into random color, producing sort of a colorful trail when you mouse over entire field of them)

**Comment by ChrisBuergi** [comment]
Thanks for the merge. 

A nice demo for the color animation would be cool. Just didn't have time yet to work on something, so the commit was just the animation.

**Comment by ChrisBuergi** [comment]
Hi, finally got time to make a better example for the color animation that is based on your idea:
http://jsfiddle.net/sad23zyz/3/

Feel free to add it to fabricjs.com

**Comment by kangax** [comment]
@ChrisBuergi awesome, thanks!
@asturur @Kienz would you guys be able to put it on fabricjs.com when you get a chance? If not, I'll get to it myself sometime soon.

**Pull request merged**
