### PR TITLE
Bug in getElementById polyfill

### LINKED ISSUE #2402: Undefined result in getElementById method(svg parser)
Hi Guys!
While using fabric 1.5.0 on node I faced with rendering issue for some SVGs. After small investigation (after I tried 1.6.0 rc) I've found that there is fix I need in 1.6.0 but it has incorrect value for idAttr property here: https://github.com/kangax/fabric.js/blob/master/src/parser.js#L385
it's empty, probably should use id agument.

### PR DESCRIPTION
**Pull request by asturur**
thanks to @bambinnesss to point it out.

closes #2402

### CODE REVIEW

**Comment by kangax** [comment]
Hm, can we add a failing test case as well?

**Comment by asturur** [comment]
in node i think yes.
i should check an existing svg load test, but being it a function, how i can call it in the test? is not sort of 'private' ?

**Comment by kangax** [comment]
We can probably test it through `parseSVGDocument`?

**Comment by asturur** [comment]
yes i need a bit of time.
My linux node box went up with some npm package and now when i run node
test i get message that with js-dom 4.x i need io.js.


2015-08-11 2:50 GMT+02:00 Juriy Zaytsev <notifications@github.com>:

**Comment by kangax** [comment]
yeah, that's why we have it locked on 1.x — https://github.com/kangax/fabric.js/blob/master/package.json#L42

**Comment by asturur** [comment]
@kangax Added failing test case for the function, ready to merge.

**Pull request merged**
