### PR TITLE
Insert a method to insert text programmatically

### LINKED ISSUE #4509: Missing method for inserting text programmatically
## Version
2.0

## Test Case
http://jsfiddle.net/redlive/jvuvm2qg/

## Steps to reproduce
1. Open JSFiddler link
2. Open dev tool
3. Run code

Basically, issue consists of 2 bugs:
1. Style js error  ( Cannot convert undefined or null to object )
2. A text does not insert

screen shot 2017-11-27 at 10 18 14 am

PS. It's unclear what function has replaced **_insertChars()_**

## Expected Behavior
New text and its style should be inserted in proper position.

## Actual Behavior
JS error

### PR DESCRIPTION
**Pull request by asturur**
close #4509 

Tests are surfacing strange behaviour of text handling.
Needs more check

### CODE REVIEW

**Comment by durga598** [comment]
Check the [fiddle](https://jsfiddle.net/durga598/47nc7bud/). Text object is in editing mode, and inserting char using insertChars(). Then try to insert via keyboard inserted char is removing. I guess we need to update hiddenTextarea value also.

**Comment by sherpa-nimesh** [comment]
Definitely this issue is kind of blocker. Once character is  inserted programatically and when trying to insert via keyboard the inserted character gets removed.

**Comment by asturur** [comment]
I missed this message. IT definitely needs a fix.

**Comment by asturur** [comment]
Can someone open an issue as a reminder?

**Pull request merged**
