### PR TITLE
Make cleaner setCoords and geometry code

### PR DESCRIPTION
**Pull request by asturur**
@knagax This PR is mainly about code clean up.
3 methods have been shrunk. Code duplication has been removed and setCoords mad ligther.
Just 4 corners are calculated using the transformation with vpt the other are find "interpolating"
mtr before was a copy of mt , and then made correct in setCornerCoords, now is calculated correct and _setCornerCoords is made simpler.

### CODE REVIEW

**Comment by kangax** [comment]
Is this good to go?

**Comment by asturur** [comment]
I did not do all that test suite.
I do not have a mirrored copy of fabricjs.com
Trying in next days

**Comment by kangax** [comment]
Ok

**Comment by asturur** [comment]
This code looks to no harm to me, i did check trought all the tests and they look visually the same.,

**Pull request merged**
